from functools import reduce

s = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis blandit turpis cursus in hac. Aenean vel elit scelerisque mauris. Risus viverra adipiscing at in tellus. Posuere morbi leo urna molestie at. Tincidunt arcu non sodales neque sodales. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum est. Tincidunt id aliquet risus feugiat in ante metus dictum at. Nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet. Cursus vitae congue mauris rhoncus aenean vel elit scelerisque mauris. Diam phasellus vestibulum lorem sed risus ultricies tristique. Faucibus a pellentesque sit amet.
Vitae tempus quam pellentesque nec. Aliquet nec ullamcorper sit amet. Sed lectus vestibulum mattis ullamcorper velit. Dignissim cras tincidunt lobortis feugiat vivamus at augue eget. Dui ut ornare lectus sit amet est placerat. Id faucibus nisl tincidunt eget nullam non nisi est sit. Et malesuada fames ac turpis egestas. Ut lectus arcu bibendum at varius vel pharetra vel turpis. Augue interdum velit euismod in pellentesque massa placerat duis. Amet cursus sit amet dictum. Vitae congue eu consequat ac felis donec et odio pellentesque. Vulputate odio ut enim blandit volutpat maecenas volutpat. Posuere lorem ipsum dolor sit amet. Erat nam at lectus urna duis convallis convallis tellus id. Aliquam sem fringilla ut morbi tincidunt augue interdum velit. Odio eu feugiat pretium nibh ipsum consequat. Placerat duis ultricies lacus sed turpis tincidunt. Arcu ac tortor dignissim convallis aenean et tortor at risus. Parturient montes nascetur ridiculus mus mauris vitae ultricies. Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi.
Tortor at risus viverra adipiscing. Faucibus vitae aliquet nec ullamcorper sit. Eleifend quam adipiscing vitae proin. Sed libero enim sed faucibus turpis. A pellentesque sit amet porttitor. Eget gravida cum sociis natoque penatibus et magnis dis. Pharetra convallis posuere morbi leo urna molestie. Metus dictum at tempor commodo ullamcorper a lacus. Id aliquet risus feugiat in ante metus dictum at. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Elementum curabitur vitae nunc sed velit dignissim. Pulvinar mattis nunc sed blandit libero. Vel risus commodo viverra maecenas accumsan lacus vel facilisis.
Tortor aliquam nulla facilisi cras. Fermentum dui faucibus in ornare. At auctor urna nunc id cursus metus aliquam eleifend. Tellus elementum sagittis vitae et. Lobortis feugiat vivamus at augue eget. Nisi scelerisque eu ultrices vitae auctor. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Turpis egestas pretium aenean pharetra magna ac. Orci a scelerisque purus semper eget duis at tellus at. Elit sed vulputate mi sit amet mauris. Et malesuada fames ac turpis egestas. Eget felis eget nunc lobortis mattis aliquam faucibus purus in. Aliquam id diam maecenas ultricies mi eget mauris pharetra. Ut consequat semper viverra nam libero justo laoreet. Vestibulum lectus mauris ultrices eros in cursus turpis. Lectus proin nibh nisl condimentum id venenatis. Non curabitur gravida arcu ac tortor dignissim convallis aenean et. Scelerisque fermentum dui faucibus in ornare quam viverra orci. Fringilla urna porttitor rhoncus dolor. Donec et odio pellentesque diam.
Mauris vitae ultricies leo integer malesuada nunc vel. Diam quam nulla porttitor massa id neque aliquam. Nam libero justo laoreet sit amet. Nec nam aliquam sem et tortor consequat id porta. Sed velit dignissim sodales ut eu sem. Elit eget gravida cum sociis natoque penatibus et. Pretium lectus quam id leo in vitae turpis massa. Ut consequat semper viverra nam libero justo. Enim ut sem viverra aliquet eget sit amet. Dignissim convallis aenean et tortor at risus. Aliquet nec ullamcorper sit amet risus nullam eget felis eget. Rutrum tellus pellentesque eu tincidunt. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Eget egestas purus viverra accumsan in nisl nisi scelerisque eu. Adipiscing bibendum est ultricies integer quis.
"""

print(
    reduce(lambda x,y: x | {y: x.get(y, 0)+1} , s, {})
)